varfish-org/varfish-server-worker

.github/workflows/release-please.yml, .github/workflows/rust.yml
This resolves some rate limiting issues.
=> ci: use GitHub token for protoc setup

Cargo.lock, Cargo.toml
=> fix: removing unused dependencies

src/sv/query/schema.rs
=> fix: specification of genomic range in query

.github/workflows/release-please.yml
=> ci: use bot token (for varfish-bot) in release-please

README.md
=> docs: fix terraform instructions in README

src/sv/query/mod.rs
=> feat: write out HGNC ids for sv query results (#150)

src/sv/query/mod.rs
=> fix: allow HGNC IDs in gene allow list

src/sv/query/bgdbs.rs
=> fix: resolve prost from_i32 deprecation

.github/workflows/rust.yml, Cargo.lock, Cargo.toml
=> chore: bumping dependencies

Cargo.toml, README.md
=> docs: updating README.md

Cargo.lock, Cargo.toml, src/common/mod.rs, src/common/noodles.rs, src/common/s3.rs, src/seqvars/ingest/mod.rs
=> feat: implement I/O from/to S3 (#234)

.github/workflows/docker-build.yml, .github/workflows/release-please.yml, utils/docker/Dockerfile, utils/docker/build-docker.sh, utils/docker/entrypoint.sh, utils/install-protoc.sh
=> feat: add build of docker containers

src/seqvars/query/schema.rs
=> chore: use serde(rename_all = "kebab-case") where appropriate

utils/docker/Dockerfile
=> ci: copy in protos for Docker builds

utils/install-protoc.sh
=> chore: use binary protoc distribution in install-protoc.sh

src/strucvars/query/schema.rs
=> fix: allow parsing FORMAT/anc as Float/f32

utils/docker/Dockerfile
=> ci: fix protoc install prefix in Dockerfile

README.md
=> docs: adding git-lfs notes to README

src/strucvars/query/schema.rs
=> fix: proper handling of FORMAT/amq

src/strucvars/query/schema.rs
=> fix: anc can be float or int

.github/workflows/docker-build.yml
=> ci: also create docker image labels for SHA

.github/workflows/protobuf.yml
=> ci: use --break-system-packages to work around issues
